#!/bin/sh
#
# Author: smoretti@isb-sib.ch
#
# /etc/init.d/tcoffee
#
# System startup script for the tcoffee server
#
### BEGIN INIT INFO
# Provides: tcoffee
# Required-Start: 
# X-UnitedLinux-Should-Start: 
# Required-Stop: 
# X-UnitedLinux-Should-Stop: 
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Play server for tcoffee
# Description:    Play server for tcoffee
### END INIT INFO

TCOFFEE_HOME=/var/lib/tcoffee
PLAY_HOME=/var/lib/tcoffee

USER=tcoffee
GROUP=cnotreda
#chmod -R tcoffee:cnotreda $TCOFFEE_HOME/tserver/

tcoffeeIsRunning()
{
  tcoffee_ps_log=`mktemp /var/tmp/tcoffee-ps.log.XXXXXX`
  ps aux --cols 1024 >"$tcoffee_ps_log"
  tcoffee_is_running="false"
  if grep "java -javaagent:$PLAY_HOME/play" "$tcoffee_ps_log" >/dev/null 2>/dev/null ; then
	tcoffee_is_running="true"
  fi
  rm -f "$tcoffee_ps_log"
  test "$tcoffee_is_running" = "true"
}



case "$1" in
    start)
		echo -n "Starting Tcoffee ($TCOFFEE_HOME)"

		if tcoffeeIsRunning ; then
	  		echo -en '\E[47;32m'"\t\t\t\talready\t\033[1mrunning\033[0m\n"
        else
			rm -f $TCOFFEE_HOME/tserver/server.pid
			rm -f /var/log/tcoffee/db/db.lock.db
	  		# try to fix permissions
			chown -R -L --dereference  $USER:$GROUP  $TCOFFEE_HOME/tserver/
			$PLAY_HOME/start.sh
	  		sleep 1

			$0 status
        fi
	;;
    stop)
		echo -n "Shutting down Tcoffee ($TCOFFEE_HOME)"

        if tcoffeeIsRunning ; then
	  		# wait 60 sec for stop at maximum
          	wait_sec=60
	  		while [ "$wait_sec" != "0" ] ; do
				$PLAY_HOME/stop.sh
	    		sleep 1
            	if ! tcoffeeIsRunning ; then
	      			# theTomcat server is stoped, end the loop
	      			wait_sec=0
	      			break
	    		fi
	    		wait_sec=$((wait_sec -1))
	  		done

			rm -f $TCOFFEE_HOME/tserver/server.pid
			$0 status
		else
	  		echo -en "\t\t\talready\t\033[1munused\033[0m\n"
		fi  
	;;
    restart)
		## Stop the service and regardless of whether it was
		## running or not, start it again.
		$0 stop
		$0 start
	;;
    status)
		echo -n "Checking for Tcoffee ($TCOFFEE_HOME)"

        if tcoffeeIsRunning ; then
        	echo -en '\E[47;32m'"\t\t\t\t\033[1mrunning\033[0m\n"
		else
	  		echo -en "\t\t\t\t\033[1munused\033[0m\n"
		fi
	;;
    *)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
	;;
esac

